// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems                     = errors.New("input MaxItems is nil")
	ErrMaxItemsItemsMaxItemsValidation = govaliderrors.ValidationError{}

	ErrMaxItemsMetadataMaxItemsValidation = govaliderrors.ValidationError{}

	ErrMaxItemsChanFieldMaxItemsValidation = govaliderrors.ValidationError{}
)

func ValidateMaxItems(t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Items) > 5 {
		err := ErrMaxItemsItemsMaxItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(t.Metadata) > 3 {
		err := ErrMaxItemsMetadataMaxItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if len(t.ChanField) > 2 {
		err := ErrMaxItemsChanFieldMaxItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
