// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilEmail is returned when the Email is nil.
	ErrNilEmail                  = errors.New("input Email is nil")
	ErrEmailEmailEmailValidation = govaliderrors.ValidationError{}
)

func ValidateEmail(t *Email) error {
	if t == nil {
		return ErrNilEmail
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrEmailEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
