// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilCEL is returned when the CEL is nil.
	ErrNilCEL              = errors.New("input CEL is nil")
	ErrCELAgeCELValidation = govaliderrors.ValidationError{}

	ErrCELNameCELValidation = govaliderrors.ValidationError{}

	ErrCELScoreCELValidation = govaliderrors.ValidationError{}

	ErrCELIsActiveCELValidation = govaliderrors.ValidationError{}
)

func ValidateCEL(t *CEL) error {
	if t == nil {
		return ErrNilCEL
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age >= 18) {
		err := ErrCELAgeCELValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if !(len(t.Name) > 0) {
		err := ErrCELNameCELValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if !(t.Score > 0) {
		err := ErrCELScoreCELValidation
		err.Value = t.Score
		errs = append(errs, err)
	}

	if !(t.IsActive == true) {
		err := ErrCELIsActiveCELValidation
		err.Value = t.IsActive
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
