// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilUUID is returned when the UUID is nil.
	ErrNilUUID                = errors.New("input UUID is nil")
	ErrUUIDUUIDUUIDValidation = govaliderrors.ValidationError{}
)

func ValidateUUID(t *UUID) error {
	if t == nil {
		return ErrNilUUID
	}

	var errs govaliderrors.ValidationErrors

	if !isValidUUID(t.UUID) {
		err := ErrUUIDUUIDUUIDValidation
		err.Value = t.UUID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
