// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*LT)(nil)

	// ErrNilLT is returned when the LT is nil.
	ErrNilLT = errors.New("input LT is nil")

	// ErrLTAgeLTValidation is the error returned when the value of the field is greater than the 10.
	ErrLTAgeLTValidation = govaliderrors.ValidationError{Reason: "field Age must be less than 10", Path: "LT.Age", Type: "lt"}
)

func ValidateLTContext(ctx context.Context, t *LT) error {
	if t == nil {
		return ErrNilLT
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !(t.Age < 10) {
		err := ErrLTAgeLTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateLT(t *LT) error {
	return ValidateLTContext(context.Background(), t)
}

func (t *LT) Validate() error {
	return ValidateLT(t)
}

func (t *LT) ValidateContext(ctx context.Context) error {
	return ValidateLTContext(ctx, t)
}
