// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*Email)(nil)

	// ErrNilEmail is returned when the Email is nil.
	ErrNilEmail = errors.New("input Email is nil")

	// ErrEmailEmailEmailValidation is the error returned when the field is not a valid email address.
	ErrEmailEmailEmailValidation = govaliderrors.ValidationError{Reason: "field Email must be a valid email address", Path: "Email.Email", Type: "email"}
)

func ValidateEmailContext(ctx context.Context, t *Email) error {
	if t == nil {
		return ErrNilEmail
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidEmail(t.Email) {
		err := ErrEmailEmailEmailValidation
		err.Value = t.Email
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateEmail(t *Email) error {
	return ValidateEmailContext(context.Background(), t)
}

func (t *Email) Validate() error {
	return ValidateEmail(t)
}

func (t *Email) ValidateContext(ctx context.Context) error {
	return ValidateEmailContext(ctx, t)
}
