// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems                     = errors.New("input MinItems is nil")
	ErrMinItemsItemsMinItemsValidation = govaliderrors.ValidationError{}

	ErrMinItemsMetadataMinItemsValidation = govaliderrors.ValidationError{}

	ErrMinItemsChanFieldMinItemsValidation = govaliderrors.ValidationError{}
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Items) < 2 {
		err := ErrMinItemsItemsMinItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(t.Metadata) < 1 {
		err := ErrMinItemsMetadataMinItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if len(t.ChanField) < 1 {
		err := ErrMinItemsChanFieldMinItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
