// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilLTE is returned when the LTE is nil.
	ErrNilLTE              = errors.New("input LTE is nil")
	ErrLTEAgeLTEValidation = govaliderrors.ValidationError{}
)

func ValidateLTE(t *LTE) error {
	if t == nil {
		return ErrNilLTE
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age <= 100) {
		err := ErrLTEAgeLTEValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
