// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"unicode/utf8"
)

var (
	// ErrNilMaxLength is returned when the MaxLength is nil.
	ErrNilMaxLength                     = errors.New("input MaxLength is nil")
	ErrMaxLengthNameMaxLengthValidation = govaliderrors.ValidationError{}
)

func ValidateMaxLength(t *MaxLength) error {
	if t == nil {
		return ErrNilMaxLength
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) > 50 {
		err := ErrMaxLengthNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
