// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*GT)(nil)

	// ErrNilGT is returned when the GT is nil.
	ErrNilGT = errors.New("input GT is nil")

	// ErrGTAgeGTValidation is the error returned when the value of the field is less than the 100.
	ErrGTAgeGTValidation = govaliderrors.ValidationError{Reason: "field Age must be greater than 100", Path: "GT.Age", Type: "gt"}
)

func ValidateGTContext(ctx context.Context, t *GT) error {
	if t == nil {
		return ErrNilGT
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !(t.Age > 100) {
		err := ErrGTAgeGTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateGT(t *GT) error {
	return ValidateGTContext(context.Background(), t)
}

func (t *GT) Validate() error {
	return ValidateGT(t)
}

func (t *GT) ValidateContext(ctx context.Context) error {
	return ValidateGTContext(ctx, t)
}
