// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems = errors.New("input MaxItems is nil")

	// ErrMaxItemsItemsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 5.
	ErrMaxItemsItemsMaxItemsValidation = govaliderrors.ValidationError{Reason: "field MaxItemsItems must have a maximum of 5 items"}

	// ErrMaxItemsMetadataMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 3.
	ErrMaxItemsMetadataMaxItemsValidation = govaliderrors.ValidationError{Reason: "field MaxItemsMetadata must have a maximum of 3 items"}

	// ErrMaxItemsChanFieldMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 2.
	ErrMaxItemsChanFieldMaxItemsValidation = govaliderrors.ValidationError{Reason: "field MaxItemsChanField must have a maximum of 2 items"}
)

func ValidateMaxItems(t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Items) > 5 {
		err := ErrMaxItemsItemsMaxItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(t.Metadata) > 3 {
		err := ErrMaxItemsMetadataMaxItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if len(t.ChanField) > 2 {
		err := ErrMaxItemsChanFieldMaxItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
