// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"unicode/utf8"
)

var (
	// ErrNilMinLength is returned when the MinLength is nil.
	ErrNilMinLength                     = errors.New("input MinLength is nil")
	ErrMinLengthNameMinLengthValidation = govaliderrors.ValidationError{}
)

func ValidateMinLength(t *MinLength) error {
	if t == nil {
		return ErrNilMinLength
	}

	var errs govaliderrors.ValidationErrors

	if utf8.RuneCountInString(t.Name) < 3 {
		err := ErrMinLengthNameMinLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
