// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilURL is returned when the URL is nil.
	ErrNilURL              = errors.New("input URL is nil")
	ErrURLURLURLValidation = govaliderrors.ValidationError{}
)

func ValidateURL(t *URL) error {
	if t == nil {
		return ErrNilURL
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidURL(t.URL) {
		err := ErrURLURLURLValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
