// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*MultipleErrors)(nil)

	// ErrNilMultipleErrors is returned when the MultipleErrors is nil.
	ErrNilMultipleErrors = errors.New("input MultipleErrors is nil")

	// ErrMultipleErrorsURLRequiredValidation is returned when the URL is required but not provided.
	ErrMultipleErrorsURLRequiredValidation = govaliderrors.ValidationError{Reason: "field URL is required", Path: "MultipleErrors.URL", Type: "required"}

	// ErrMultipleErrorsTooLongMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 1.
	ErrMultipleErrorsTooLongMaxLengthValidation = govaliderrors.ValidationError{Reason: "field TooLong must have a maximum length of 1", Path: "MultipleErrors.TooLong", Type: "maxlength"}
)

func ValidateMultipleErrorsContext(ctx context.Context, t *MultipleErrors) error {
	if t == nil {
		return ErrNilMultipleErrors
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.URL == "" {
		err := ErrMultipleErrorsURLRequiredValidation
		err.Value = t.URL
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.TooLong) > 1 {
		err := ErrMultipleErrorsTooLongMaxLengthValidation
		err.Value = t.TooLong
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateMultipleErrors(t *MultipleErrors) error {
	return ValidateMultipleErrorsContext(context.Background(), t)
}

func (t *MultipleErrors) Validate() error {
	return ValidateMultipleErrors(t)
}

func (t *MultipleErrors) ValidateContext(ctx context.Context) error {
	return ValidateMultipleErrorsContext(ctx, t)
}
