// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*MaxLength)(nil)

	// ErrNilMaxLength is returned when the MaxLength is nil.
	ErrNilMaxLength = errors.New("input MaxLength is nil")

	// ErrMaxLengthNameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 50.
	ErrMaxLengthNameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Name must have a maximum length of 50", Path: "MaxLength.Name", Type: "maxlength"}
)

func ValidateMaxLengthContext(ctx context.Context, t *MaxLength) error {
	if t == nil {
		return ErrNilMaxLength
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.Name) > 50 {
		err := ErrMaxLengthNameMaxLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateMaxLength(t *MaxLength) error {
	return ValidateMaxLengthContext(context.Background(), t)
}

func (t *MaxLength) Validate() error {
	return ValidateMaxLength(t)
}

func (t *MaxLength) ValidateContext(ctx context.Context) error {
	return ValidateMaxLengthContext(ctx, t)
}
