// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*Alphanum)(nil)

	// ErrNilAlphanum is returned when the Alphanum is nil.
	ErrNilAlphanum = errors.New("input Alphanum is nil")

	// ErrAlphanumProductCodeAlphanumValidation is the error returned when field ProductCode is not alphanumeric.
	ErrAlphanumProductCodeAlphanumValidation = govaliderrors.ValidationError{Reason: "field ProductCode must be alphanumeric", Path: "Alphanum.ProductCode", Type: "alphanum"}

	// ErrAlphanumSerialNumberAlphanumValidation is the error returned when field SerialNumber is not alphanumeric.
	ErrAlphanumSerialNumberAlphanumValidation = govaliderrors.ValidationError{Reason: "field SerialNumber must be alphanumeric", Path: "Alphanum.SerialNumber", Type: "alphanum"}

	// ErrAlphanumUsernameAlphanumValidation is the error returned when field Username is not alphanumeric.
	ErrAlphanumUsernameAlphanumValidation = govaliderrors.ValidationError{Reason: "field Username must be alphanumeric", Path: "Alphanum.Username", Type: "alphanum"}
)

func ValidateAlphanumContext(ctx context.Context, t *Alphanum) error {
	if t == nil {
		return ErrNilAlphanum
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidAlphanum(t.ProductCode) {
		err := ErrAlphanumProductCodeAlphanumValidation
		err.Value = t.ProductCode
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidAlphanum(t.SerialNumber) {
		err := ErrAlphanumSerialNumberAlphanumValidation
		err.Value = t.SerialNumber
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsValidAlphanum(t.Username) {
		err := ErrAlphanumUsernameAlphanumValidation
		err.Value = t.Username
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateAlphanum(t *Alphanum) error {
	return ValidateAlphanumContext(context.Background(), t)
}

func (t *Alphanum) Validate() error {
	return ValidateAlphanum(t)
}

func (t *Alphanum) ValidateContext(ctx context.Context) error {
	return ValidateAlphanumContext(ctx, t)
}
