// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	"regexp"
)

var (
	// ErrNilUUID is returned when the UUID is nil.
	ErrNilUUID = errors.New("input UUID is nil")

	// uuidRegex is the compiled regex pattern for UUID validation.
	uuidRegex = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$")
	// ErrUUIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrUUIDUUIDValidation = errors.New("field UUID must be a valid UUID")
)

func ValidateUUID(t *UUID) error {
	if t == nil {
		return ErrNilUUID
	}

	if !uuidRegex.MatchString(t.UUID) {
		return ErrUUIDUUIDValidation
	}

	return nil
}
