// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGTE is returned when the GTE is nil.
	ErrNilGTE              = errors.New("input GTE is nil")
	ErrGTEAgeGTEValidation = govaliderrors.ValidationError{}
)

func ValidateGTE(t *GTE) error {
	if t == nil {
		return ErrNilGTE
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age >= 18) {
		err := ErrGTEAgeGTEValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
