// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"
	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*Length)(nil)

	// ErrNilLength is returned when the Length is nil.
	ErrNilLength = errors.New("input Length is nil")

	// ErrLengthNameLengthValidation is the error returned when the length of the field is not exactly 7.
	ErrLengthNameLengthValidation = govaliderrors.ValidationError{Reason: "field Name length must be exactly 7", Path: "Length.Name", Type: "length"}
)

func ValidateLengthContext(ctx context.Context, t *Length) error {
	if t == nil {
		return ErrNilLength
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.Name) != 7 {
		err := ErrLengthNameLengthValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateLength(t *Length) error {
	return ValidateLengthContext(context.Background(), t)
}

func (t *Length) Validate() error {
	return ValidateLength(t)
}

func (t *Length) ValidateContext(ctx context.Context) error {
	return ValidateLengthContext(ctx, t)
}
