// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilRequired is returned when the Required is nil.
	ErrNilRequired                    = errors.New("input Required is nil")
	ErrRequiredNameRequiredValidation = govaliderrors.ValidationError{}

	ErrRequiredAgeRequiredValidation = govaliderrors.ValidationError{}

	ErrRequiredItemsRequiredValidation = govaliderrors.ValidationError{}
)

func ValidateRequired(t *Required) error {
	if t == nil {
		return ErrNilRequired
	}

	var errs govaliderrors.ValidationErrors

	if t.Name == "" {
		err := ErrRequiredNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if t.Age == 0 {
		err := ErrRequiredAgeRequiredValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if t.Items == nil {
		err := ErrRequiredItemsRequiredValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
