// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilCELCrossField is returned when the CELCrossField is nil.
	ErrNilCELCrossField                = errors.New("input CELCrossField is nil")
	ErrCELCrossFieldPriceCELValidation = govaliderrors.ValidationError{}

	ErrCELCrossFieldQuantityCELValidation = govaliderrors.ValidationError{}
)

func ValidateCELCrossField(t *CELCrossField) error {
	if t == nil {
		return ErrNilCELCrossField
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Price < t.MaxPrice) {
		err := ErrCELCrossFieldPriceCELValidation
		err.Value = t.Price
		errs = append(errs, err)
	}

	if !(t.Quantity*t.Price <= t.Budget) {
		err := ErrCELCrossFieldQuantityCELValidation
		err.Value = t.Quantity
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
