// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*MaxItems)(nil)

	// ErrNilMaxItems is returned when the MaxItems is nil.
	ErrNilMaxItems = errors.New("input MaxItems is nil")

	// ErrMaxItemsItemsMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 5.
	ErrMaxItemsItemsMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Items must have a maximum of 5 items", Path: "MaxItems.Items", Type: "maxitems"}

	// ErrMaxItemsMetadataMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 3.
	ErrMaxItemsMetadataMaxItemsValidation = govaliderrors.ValidationError{Reason: "field Metadata must have a maximum of 3 items", Path: "MaxItems.Metadata", Type: "maxitems"}

	// ErrMaxItemsChanFieldMaxItemsValidation is the error returned when the length of the field exceeds the maximum of 2.
	ErrMaxItemsChanFieldMaxItemsValidation = govaliderrors.ValidationError{Reason: "field ChanField must have a maximum of 2 items", Path: "MaxItems.ChanField", Type: "maxitems"}
)

func ValidateMaxItemsContext(ctx context.Context, t *MaxItems) error {
	if t == nil {
		return ErrNilMaxItems
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.Items) > 5 {
		err := ErrMaxItemsItemsMaxItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.Metadata) > 3 {
		err := ErrMaxItemsMetadataMaxItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.ChanField) > 2 {
		err := ErrMaxItemsChanFieldMaxItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateMaxItems(t *MaxItems) error {
	return ValidateMaxItemsContext(context.Background(), t)
}

func (t *MaxItems) Validate() error {
	return ValidateMaxItems(t)
}

func (t *MaxItems) ValidateContext(ctx context.Context) error {
	return ValidateMaxItemsContext(ctx, t)
}
