// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilGT is returned when the GT is nil.
	ErrNilGT             = errors.New("input GT is nil")
	ErrGTAgeGTValidation = govaliderrors.ValidationError{}
)

func ValidateGT(t *GT) error {
	if t == nil {
		return ErrNilGT
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age > 100) {
		err := ErrGTAgeGTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
