// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrMinItemsItemsMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrMinItemsItemsMinItemsValidation = govaliderrors.ValidationError{Reason: "field MinItemsItems must have a minimum of 2 items"}

	// ErrMinItemsMetadataMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsMetadataMinItemsValidation = govaliderrors.ValidationError{Reason: "field MinItemsMetadata must have a minimum of 1 items"}

	// ErrMinItemsChanFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsChanFieldMinItemsValidation = govaliderrors.ValidationError{Reason: "field MinItemsChanField must have a minimum of 1 items"}
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	var errs govaliderrors.ValidationErrors

	if len(t.Items) < 2 {
		err := ErrMinItemsItemsMinItemsValidation
		err.Value = t.Items
		errs = append(errs, err)
	}

	if len(t.Metadata) < 1 {
		err := ErrMinItemsMetadataMinItemsValidation
		err.Value = t.Metadata
		errs = append(errs, err)
	}

	if len(t.ChanField) < 1 {
		err := ErrMinItemsChanFieldMinItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
