// Code generated by govalid; DO NOT EDIT.
package test

import (
	"context"
	"errors"

	"net"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*IPV6)(nil)

	// ErrNilIPV6 is returned when the IPV6 is nil.
	ErrNilIPV6 = errors.New("input IPV6 is nil")

	// ErrIPV6IPIpv6Validation is returned when the IP fails ipv6 validation.
	ErrIPV6IPIpv6Validation = govaliderrors.ValidationError{Reason: "field IP failed ipv6 validation", Path: "IPV6.IP", Type: "ipv6"}
)

func ValidateIPV6Context(ctx context.Context, t *IPV6) error {
	if t == nil {
		return ErrNilIPV6
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if ip := net.ParseIP(t.IP); ip == nil || ip.To4() != nil {
		err := ErrIPV6IPIpv6Validation
		err.Value = t.IP
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateIPV6(t *IPV6) error {
	return ValidateIPV6Context(context.Background(), t)
}

func (t *IPV6) Validate() error {
	return ValidateIPV6(t)
}

func (t *IPV6) ValidateContext(ctx context.Context) error {
	return ValidateIPV6Context(ctx, t)
}
