// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilLTE is returned when the LTE is nil.
	ErrNilLTE = errors.New("input LTE is nil")

	// ErrScoreLTEValidation is the error returned when the value of the field is greater than 100.
	ErrScoreLTEValidation = errors.New("field Score must be less than or equal to 100")
)

func ValidateLTE(t *LTE) error {
	if t == nil {
		return ErrNilLTE
	}

	if !(t.Score <= 100) {
		return ErrScoreLTEValidation
	}

	return nil
}