// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	// ErrNilLT is returned when the LT is nil.
	ErrNilLT = errors.New("input LT is nil")

	// ErrLTAgeLTValidation is the error returned when the value of the field is greater than the %s.
	ErrLTAgeLTValidation = govaliderrors.ValidationError{Reason: "field LTAge must be less than %s", Path: "LT.Age"}
)

func ValidateLT(t *LT) error {
	if t == nil {
		return ErrNilLT
	}

	var errs govaliderrors.ValidationErrors

	if !(t.Age < 10) {
		err := ErrLTAgeLTValidation
		err.Type = "LT"
		err.Value = t.Age
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}
