// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilEnum is returned when the Enum is nil.
	ErrNilEnum = errors.New("input Enum is nil")

	// ErrRoleEnumValidation is the error returned when the value of the field is not one of the allowed values: admin user guest.
	ErrRoleEnumValidation = errors.New("field Role must be one of the allowed values: admin user guest")
)

func ValidateEnum(t *Enum) error {
	if t == nil {
		return ErrNilEnum
	}

	if t.Role != "admin" && t.Role != "user" && t.Role != "guest" {
		return ErrRoleEnumValidation
	}

	return nil
}