// Code generated by govalid; DO NOT EDIT.
package test

import (
	"errors"
)

var (
	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrItemsMinItemsValidation is the error returned when the length of the field is below the minimum of 2.
	ErrItemsMinItemsValidation = errors.New("field Items must have a minimum of 2 items")
)

func ValidateMinItems(t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	if len(t.Items) < 2 {
		return ErrItemsMinItemsValidation
	}

	return nil
}