// Code generated by generate-validators; DO NOT EDIT.
package rules

import (
	"fmt"
	"go/ast"
	"go/types"
	"strings"

	"github.com/gostaticanalysis/codegen"

	"github.com/sivchari/govalid/internal/validator"
)

type alphanumValidator struct {
	pass       *codegen.Pass
	field      *ast.Field
	structName string
}

var _ validator.Validator = (*alphanumValidator)(nil)

const alphanumKey = "%s-alphanum"

func (v *alphanumValidator) Validate() string {
	fieldName := v.FieldName()
	return fmt.Sprintf("!isAlphaNumeric(t.%s)", fieldName)
}

func (v *alphanumValidator) FieldName() string {
	return v.field.Names[0].Name
}

func (v *alphanumValidator) generateValidationFunction() string {
	return `
		isAlphaNumeric = func(s string) bool {
			for _, r := range s {
				if (r < 'a' || r > 'z') &&
					(r < 'A' || r > 'Z') &&
					(r < '0' || r > '9') {
					return false
				}
			}
			return s != ""
		}
	`
}

func (v *alphanumValidator) Err() string {
	fieldName := v.FieldName()

	var result strings.Builder

	// Generate isValidAlphanum function only once
	if !validator.GeneratorMemory["alphanum-function-generated"] {
		validator.GeneratorMemory["alphanum-function-generated"] = true
		result.WriteString(v.generateValidationFunction())
	}

	key := fmt.Sprintf(alphanumKey, v.structName+fieldName)
	if validator.GeneratorMemory[key] {
		return result.String()
	}

	validator.GeneratorMemory[key] = true

	result.WriteString(strings.ReplaceAll(`
	// Err@AlphanumValidation is returned when the @ fails alphanum validation.
	Err@AlphanumValidation = errors.New("field @ failed alphanum validation")`, "@", v.structName+fieldName))

	return result.String()
}

func (v *alphanumValidator) ErrVariable() string {
	return strings.ReplaceAll("Err@AlphanumValidation", "@", v.structName+v.FieldName())
}

func (v *alphanumValidator) Imports() []string {
	return []string{}
}

// ValidateAlphanum creates a new alphanum validator for the given field.
func ValidateAlphanum(pass *codegen.Pass, field *ast.Field, expressions map[string]string, structName string) validator.Validator {
	validator.GeneratorMemory[fmt.Sprintf(alphanumKey, structName+field.Names[0].Name)] = false

	typ := pass.TypesInfo.TypeOf(field.Type)
	basic, ok := typ.Underlying().(*types.Basic)

	if !ok || basic.Kind() != types.String {
		return nil
	}

	return &alphanumValidator{
		pass:       pass,
		field:      field,
		structName: structName,
	}
}
