/*
Scaffold generated by govalid generate-validators. Edit this file to implement validation logic.
*/

package rules

import (
	"fmt"
	"go/ast"
	"strings"

	"github.com/gostaticanalysis/codegen"

	"github.com/sivchari/govalid/internal/validator"
	"github.com/sivchari/govalid/internal/validator/registry"
)

type ipv4Validator struct {
	pass       *codegen.Pass
	field      *ast.Field
	structName string
	ruleName   string
	parentPath string
}

var _ validator.Validator = (*ipv4Validator)(nil)

func (v *ipv4Validator) Validate() string {
	return fmt.Sprintf("ip := net.ParseIP(t.%s); ip == nil || ip.To4() == nil", v.FieldName())
}

func (v *ipv4Validator) FieldName() string {
	return v.field.Names[0].Name
}

func (v *ipv4Validator) FieldPath() validator.FieldPath {
	return validator.NewFieldPath(v.structName, v.parentPath, v.FieldName())
}

func (v *ipv4Validator) Err() string {
	const errTemplate = `
	  // [@ERRVARIABLE] is returned when the [@FIELD] fails ipv4 validation.
	  [@ERRVARIABLE] = govaliderrors.ValidationError{Reason:"field [@FIELD] failed ipv4 validation",Path:"[@PATH]",Type:"[@TYPE]"}
	`

	replacer := strings.NewReplacer(
		"[@ERRVARIABLE]", v.ErrVariable(),
		"[@FIELD]", v.FieldName(),
		"[@PATH]", v.FieldPath().String(),
		"[@TYPE]", v.ruleName,
	)

	return replacer.Replace(errTemplate)
}

func (v *ipv4Validator) ErrVariable() string {
	return strings.ReplaceAll("Err[@PATH]Ipv4Validation", "[@PATH]", v.FieldPath().CleanedPath())
}

func (v *ipv4Validator) Imports() []string {
	return []string{"net"}
}

// ValidateIpv4 creates a new ipv4 validator for the given field.
func ValidateIpv4(input registry.ValidatorInput) validator.Validator {
	return &ipv4Validator{
		pass:       input.Pass,
		field:      input.Field,
		structName: input.StructName,
		ruleName:   input.RuleName,
		parentPath: input.ParentPath,
	}
}
