// Code generated by govalid; DO NOT EDIT.
package ipv4

import (
	"context"
	"errors"

	"net"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*IPv4)(nil)

	// ErrNilIPv4 is returned when the IPv4 is nil.
	ErrNilIPv4 = errors.New("input IPv4 is nil")

	// ErrIPv4ValueIpv4Validation is returned when the Value fails ipv4 validation.
	ErrIPv4ValueIpv4Validation = govaliderrors.ValidationError{Reason: "field Value failed ipv4 validation", Path: "IPv4.Value", Type: "ipv4"}
)

func ValidateIPv4Context(ctx context.Context, t *IPv4) error {
	if t == nil {
		return ErrNilIPv4
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if ip := net.ParseIP(t.Value); ip == nil || ip.To4() == nil {
		err := ErrIPv4ValueIpv4Validation
		err.Value = t.Value
		errs = append(errs, err)
	}

	{
		if ctx.Err() != nil {
			return ctx.Err()
		}

		t := t.Struct

		if ip := net.ParseIP(t.Value); ip == nil || ip.To4() == nil {
			err := ErrIPv4ValueIpv4Validation
			err.Value = t.Value
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateIPv4(t *IPv4) error {
	return ValidateIPv4Context(context.Background(), t)
}

func (t *IPv4) Validate() error {
	return ValidateIPv4(t)
}

func (t *IPv4) ValidateContext(ctx context.Context) error {
	return ValidateIPv4Context(ctx, t)
}
