// Code generated by govalid; DO NOT EDIT.
package minitems

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*MinItems)(nil)

	// ErrNilMinItems is returned when the MinItems is nil.
	ErrNilMinItems = errors.New("input MinItems is nil")

	// ErrMinItemsSliceMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrMinItemsSliceMinItemsValidation = govaliderrors.ValidationError{Reason: "field Slice must have a minimum of 2 items", Path: "MinItems.Slice", Type: "minitems"}

	// ErrMinItemsArrayMinItemsValidation is the error returned when the length of the field is less than the minimum of 3.
	ErrMinItemsArrayMinItemsValidation = govaliderrors.ValidationError{Reason: "field Array must have a minimum of 3 items", Path: "MinItems.Array", Type: "minitems"}

	// ErrMinItemsMapFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsMapFieldMinItemsValidation = govaliderrors.ValidationError{Reason: "field MapField must have a minimum of 1 items", Path: "MinItems.MapField", Type: "minitems"}

	// ErrMinItemsChanFieldMinItemsValidation is the error returned when the length of the field is less than the minimum of 2.
	ErrMinItemsChanFieldMinItemsValidation = govaliderrors.ValidationError{Reason: "field ChanField must have a minimum of 2 items", Path: "MinItems.ChanField", Type: "minitems"}

	// Deprecated: Use ErrMinItemsStructItemsMinItemsValidation
	//
	// ErrMinItemsItemsMinItemsValidation is deprecated and is kept for compatibility purpose.
	ErrMinItemsItemsMinItemsValidation = ErrMinItemsStructItemsMinItemsValidation

	// ErrMinItemsStructItemsMinItemsValidation is the error returned when the length of the field is less than the minimum of 1.
	ErrMinItemsStructItemsMinItemsValidation = govaliderrors.ValidationError{Reason: "field Items must have a minimum of 1 items", Path: "MinItems.Struct.Items", Type: "minitems"}
)

func ValidateMinItemsContext(ctx context.Context, t *MinItems) error {
	if t == nil {
		return ErrNilMinItems
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.Slice) < 2 {
		err := ErrMinItemsSliceMinItemsValidation
		err.Value = t.Slice
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.Array) < 3 {
		err := ErrMinItemsArrayMinItemsValidation
		err.Value = t.Array
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.MapField) < 1 {
		err := ErrMinItemsMapFieldMinItemsValidation
		err.Value = t.MapField
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if len(t.ChanField) < 2 {
		err := ErrMinItemsChanFieldMinItemsValidation
		err.Value = t.ChanField
		errs = append(errs, err)
	}

	{
		t := t.Struct
		if ctx.Err() != nil {
			return ctx.Err()
		}

		if len(t.Items) < 1 {
			err := ErrMinItemsStructItemsMinItemsValidation
			err.Value = t.Items
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateMinItems(t *MinItems) error {
	return ValidateMinItemsContext(context.Background(), t)
}

func (t *MinItems) Validate() error {
	return ValidateMinItems(t)
}

func (t *MinItems) ValidateContext(ctx context.Context) error {
	return ValidateMinItemsContext(ctx, t)
}
