// Code generated by govalid; DO NOT EDIT.
package inside

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
)

var (
	_ govalid.Validator = (*Inside)(nil)

	// ErrNilInside is returned when the Inside is nil.
	ErrNilInside = errors.New("input Inside is nil")

	// Deprecated: Use ErrInsideAXRequiredValidation
	//
	// ErrInsideXRequiredValidation is deprecated and is kept for compatibility purpose.
	ErrInsideXRequiredValidation = ErrInsideAXRequiredValidation

	// ErrInsideAXRequiredValidation is returned when the X is required but not provided.
	ErrInsideAXRequiredValidation = govaliderrors.ValidationError{Reason: "field X is required", Path: "Inside.A.X", Type: "required"}
)

func ValidateInsideContext(ctx context.Context, t *Inside) error {
	if t == nil {
		return ErrNilInside
	}

	var errs govaliderrors.ValidationErrors

	{
		if ctx.Err() != nil {
			return ctx.Err()
		}

		t := t.A

		if t.X == "" {
			err := ErrInsideAXRequiredValidation
			err.Value = t.X
			errs = append(errs, err)
		}

	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateInside(t *Inside) error {
	return ValidateInsideContext(context.Background(), t)
}

func (t *Inside) Validate() error {
	return ValidateInside(t)
}

func (t *Inside) ValidateContext(ctx context.Context) error {
	return ValidateInsideContext(ctx, t)
}
