// Code generated by govalid; DO NOT EDIT.
package numeric

import (
	"context"
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	_ govalid.Validator = (*Numeric)(nil)

	// ErrNilNumeric is returned when the Numeric is nil.
	ErrNilNumeric = errors.New("input Numeric is nil")

	// ErrNumericNumberNumericValidation is the error returned when the field Number is not numeric.
	ErrNumericNumberNumericValidation = govaliderrors.ValidationError{Reason: "field Number must be numeric", Path: "Numeric.Number", Type: "numeric"}
)

func ValidateNumericContext(ctx context.Context, t *Numeric) error {
	if t == nil {
		return ErrNilNumeric
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !validationhelper.IsNumeric(t.Number) {
		err := ErrNumericNumberNumericValidation
		err.Value = t.Number
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

func ValidateNumeric(t *Numeric) error {
	return ValidateNumericContext(context.Background(), t)
}

func (t *Numeric) Validate() error {
	return ValidateNumeric(t)
}

func (t *Numeric) ValidateContext(ctx context.Context) error {
	return ValidateNumericContext(ctx, t)
}
