// Code generated by govalid; DO NOT EDIT.
package uuid

import (
	"errors"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"github.com/sivchari/govalid/validation/validationhelper"
)

var (
	// ErrNilUUID is returned when the UUID is nil.
	ErrNilUUID = errors.New("input UUID is nil")

	// ErrUUIDUUIDUUIDValidation is the error returned when the field is not a valid UUID.
	ErrUUIDUUIDUUIDValidation = govaliderrors.ValidationError{Reason: "field UUID must be a valid UUID", Path: "UUID.UUID", Type: "uuid"}
)

func ValidateUUID(t *UUID) error {
	if t == nil {
		return ErrNilUUID
	}

	var errs govaliderrors.ValidationErrors

	if !validationhelper.IsValidUUID(t.UUID) {
		err := ErrUUIDUUIDUUIDValidation
		err.Value = t.UUID
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return errs
	}
	return nil
}

var _ govalid.Validator = (*UUID)(nil)

func (t *UUID) Validate() error {
	return ValidateUUID(t)
}
