// Code generated by govalid; DO NOT EDIT.
package i18n

import (
	"context"
	"errors"

	"unicode/utf8"

	"github.com/sivchari/govalid"
	govaliderrors "github.com/sivchari/govalid/validation/errors"
	"golang.org/x/text/language"
)

var (
	_ govalid.Validator = (*User)(nil)

	// ErrNilUser is returned when the User is nil.
	ErrNilUser = errors.New("input User is nil")

	// ErrUserNameRequiredValidation is returned when the Name is required but not provided.
	ErrUserNameRequiredValidation = govaliderrors.ValidationError{Reason: "field Name is required", Path: "User.Name", Type: "required", Messages: map[language.Tag]string{language.Make("fr"): "Name est obligatoire", language.Make("ja"): "Nameは必須です"}}

	// ErrUserAgeGTValidation is the error returned when the value of the field is less than the 18.
	ErrUserAgeGTValidation = govaliderrors.ValidationError{Reason: "field Age must be greater than 18", Path: "User.Age", Type: "gt", Messages: map[language.Tag]string{language.Make("fr"): "Age doit être supérieur à 18", language.Make("ja"): "Ageは18より大きい値にしてください"}}

	// ErrUserNicknameMaxLengthValidation is the error returned when the length of the field exceeds the maximum of 20.
	ErrUserNicknameMaxLengthValidation = govaliderrors.ValidationError{Reason: "field Nickname must have a maximum length of 20", Path: "User.Nickname", Type: "maxlength", Messages: map[language.Tag]string{language.Make("ja"): "Nicknameは20文字以内にしてください"}}
)

func ValidateUserContext(ctx context.Context, t *User) error {
	if t == nil {
		return ErrNilUser
	}

	var errs govaliderrors.ValidationErrors

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if t.Name == "" {
		err := ErrUserNameRequiredValidation
		err.Value = t.Name
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if !(t.Age > 18) {
		err := ErrUserAgeGTValidation
		err.Value = t.Age
		errs = append(errs, err)
	}

	if ctx.Err() != nil {
		return ctx.Err()
	}

	if utf8.RuneCountInString(t.Nickname) > 20 {
		err := ErrUserNicknameMaxLengthValidation
		err.Value = t.Nickname
		errs = append(errs, err)
	}

	if len(errs) > 0 {
		return govalid.Localize(ctx, errs)
	}
	return nil
}

func ValidateUser(t *User) error {
	return ValidateUserContext(context.Background(), t)
}

func (t *User) Validate() error {
	return ValidateUser(t)
}

func (t *User) ValidateContext(ctx context.Context) error {
	return ValidateUserContext(ctx, t)
}
