name: Check Benchmark Synchronization

on:
  pull_request:
    paths:
      - 'test/benchmark/**'
      - 'docs/content/benchmarks.md'
      - 'docs/content/_index.md'
      - '.github/workflows/check-benchmark-sync.yml'
  push:
    branches: [main]
    paths:
      - 'test/benchmark/**'
      - 'docs/content/benchmarks.md'
      - 'docs/content/_index.md'

jobs:
  check-sync:
    name: Check Benchmark Sync
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      
      - name: Check benchmark synchronization
        run: make check-benchmark-sync
        env:
          CI: true
      
      - name: Comment on PR if out of sync
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `⚠️ **Benchmark Synchronization Issue**
              
              The benchmark results in your documentation files are not synchronized.
              
              This usually happens when:
              - \`test/benchmark/README.md\` has different data than \`docs/content/benchmarks.md\`
              - The homepage performance table is outdated
              - Benchmark dates don't match
              
              **To fix this:**
              \`\`\`bash
              make sync-benchmarks
              git add test/benchmark/README.md docs/content/benchmarks.md docs/content/_index.md
              git commit -m "Sync benchmark results across documentation"
              \`\`\`
              
              **To verify the fix:**
              \`\`\`bash
              make check-benchmark-sync
              \`\`\`
              `
            })
      
      - name: Validate benchmark data freshness
        if: success()
        run: |
          echo "✅ Benchmark synchronization check passed"
          echo "📊 All documentation files contain consistent benchmark data"