name: Vulnerability Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1' # every Monday at 03:00 UTC (12:00 JST)

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run govulncheck
        id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          go-package: ./...
          output-file: govulncheck.log

      - name: Upload govulncheck report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: govulncheck-report
          path: govulncheck.log
