name: Pinact Check

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  pinact-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install pinact
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: suzuki-shunsuke/pinact
          tag: v3.9.0

      - name: Run pinact check
        run: pinact run --check
